import { db } from "./db";
import { categories, products } from "@shared/schema";

const sampleCategories = [
  {
    name: "Vegetables",
    slug: "vegetables",
    description: "Fresh and organic vegetables sourced directly from farms",
    imageUrl: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=120",
    isActive: true,
  },
  {
    name: "Fruits",
    slug: "fruits", 
    description: "Seasonal fresh fruits packed with natural goodness",
    imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=120",
    isActive: true,
  },
  {
    name: "Dairy",
    slug: "dairy",
    description: "Farm fresh dairy products and milk",
    imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=120",
    isActive: true,
  },
  {
    name: "Snacks",
    slug: "snacks",
    description: "Healthy snacks and packaged foods",
    imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=120",
    isActive: true,
  },
  {
    name: "Beverages",
    slug: "beverages",
    description: "Refreshing drinks and healthy beverages",
    imageUrl: "https://images.unsplash.com/photo-1544145945-f90425340c7e?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=120",
    isActive: true,
  },
];

export async function seedDatabase() {
  try {
    console.log("Starting database seeding...");

    // Clear existing data
    await db.delete(products);
    await db.delete(categories);

    // Insert categories
    console.log("Inserting categories...");
    const insertedCategories = await db.insert(categories).values(sampleCategories).returning();
    
    const categoryMap = new Map();
    insertedCategories.forEach(cat => {
      categoryMap.set(cat.slug, cat.id);
    });

    // Sample products for each category
    const sampleProducts = [
      // Vegetables
      {
        name: "Organic Tomatoes",
        description: "Fresh, juicy organic tomatoes perfect for cooking and salads",
        price: "60.00",
        originalPrice: "80.00",
        weight: "1 kg",
        unit: "kg",
        imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 50,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Fresh Onions",
        description: "Premium quality onions, essential for every kitchen",
        price: "40.00",
        originalPrice: "50.00",
        weight: "1 kg",
        unit: "kg",
        imageUrl: "https://images.unsplash.com/photo-1508747703725-719777637510?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 75,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Bell Peppers",
        description: "Colorful bell peppers rich in vitamins and antioxidants",
        price: "120.00",
        originalPrice: "150.00",
        weight: "500g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1525607551316-4a8e16d1c30b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 30,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Fresh Carrots",
        description: "Sweet and crunchy carrots, perfect for snacking and cooking",
        price: "45.00",
        weight: "500g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 60,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Green Spinach",
        description: "Fresh leafy spinach packed with iron and nutrients",
        price: "35.00",
        weight: "250g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 40,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Fresh Potatoes",
        description: "Premium quality potatoes for all your cooking needs",
        price: "30.00",
        weight: "1 kg",
        unit: "kg",
        imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 100,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Green Broccoli",
        description: "Fresh broccoli florets rich in vitamins and minerals",
        price: "80.00",
        weight: "500g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 25,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Fresh Cucumber",
        description: "Crisp and refreshing cucumbers perfect for salads",
        price: "25.00",
        weight: "500g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 45,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Green Capsicum",
        description: "Fresh green capsicum with a crisp texture and mild flavor",
        price: "50.00",
        weight: "250g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 35,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },
      {
        name: "Fresh Cauliflower",
        description: "Premium white cauliflower perfect for various dishes",
        price: "60.00",
        weight: "1 piece",
        unit: "piece",
        imageUrl: "https://images.unsplash.com/photo-1568584711271-9f4c71de25e6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 20,
        categoryId: categoryMap.get("vegetables"),
        isActive: true,
      },

      // Fruits
      {
        name: "Fresh Bananas",
        description: "Sweet and ripe bananas rich in potassium",
        price: "40.00",
        weight: "1 dozen",
        unit: "dozen",
        imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 80,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Red Apples",
        description: "Crisp and sweet red apples, perfect for snacking",
        price: "150.00",
        originalPrice: "180.00",
        weight: "1 kg",
        unit: "kg",
        imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 60,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Fresh Oranges",
        description: "Juicy oranges packed with vitamin C",
        price: "80.00",
        weight: "1 kg",
        unit: "kg",
        imageUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 45,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Green Grapes",
        description: "Sweet and seedless green grapes",
        price: "120.00",
        weight: "500g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 30,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Fresh Mangoes",
        description: "Sweet and juicy mangoes, the king of fruits",
        price: "200.00",
        originalPrice: "250.00",
        weight: "1 kg",
        unit: "kg",
        imageUrl: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 25,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Fresh Pineapple",
        description: "Sweet and tangy pineapple rich in vitamins",
        price: "90.00",
        weight: "1 piece",
        unit: "piece",
        imageUrl: "https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 15,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Fresh Watermelon",
        description: "Refreshing watermelon perfect for summer",
        price: "40.00",
        weight: "1 kg",
        unit: "kg",
        imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 20,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Fresh Strawberries",
        description: "Sweet and juicy strawberries rich in antioxidants",
        price: "180.00",
        weight: "250g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 10,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Fresh Kiwi",
        description: "Tangy kiwi fruits packed with vitamin C",
        price: "160.00",
        weight: "500g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1585059895524-72359e06133a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 20,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },
      {
        name: "Fresh Pomegranate",
        description: "Antioxidant-rich pomegranate with ruby red seeds",
        price: "140.00",
        weight: "500g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1553575457-d5d18c4f0fb1?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 25,
        categoryId: categoryMap.get("fruits"),
        isActive: true,
      },

      // Dairy
      {
        name: "Fresh Milk",
        description: "Pure and fresh milk from local dairy farms",
        price: "55.00",
        weight: "1 liter",
        unit: "liter",
        imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 100,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Greek Yogurt",
        description: "Creamy Greek yogurt rich in protein and probiotics",
        price: "120.00",
        weight: "500g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1571212515967-df95b33e1ea9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 40,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Fresh Cheese",
        description: "Premium quality fresh cheese for cooking and snacking",
        price: "200.00",
        weight: "250g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 30,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Fresh Butter",
        description: "Creamy fresh butter made from pure milk cream",
        price: "180.00",
        weight: "200g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 50,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Cottage Cheese",
        description: "Fresh cottage cheese high in protein and low in fat",
        price: "160.00",
        weight: "200g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 35,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Fresh Cream",
        description: "Rich and thick cream perfect for cooking and desserts",
        price: "140.00",
        weight: "200ml",
        unit: "ml",
        imageUrl: "https://images.unsplash.com/photo-1563379091839-d5acc2ce0e84?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 25,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Mozzarella Cheese",
        description: "Premium mozzarella cheese perfect for pizzas and pasta",
        price: "250.00",
        weight: "200g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 20,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Cheddar Cheese",
        description: "Aged cheddar cheese with rich and sharp flavor",
        price: "300.00",
        weight: "200g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1452195100486-9cc805987862?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 15,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Flavored Yogurt",
        description: "Delicious flavored yogurt available in multiple varieties",
        price: "80.00",
        weight: "400g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1571212515967-df95b33e1ea9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 60,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },
      {
        name: "Paneer",
        description: "Fresh homemade paneer perfect for Indian cuisine",
        price: "220.00",
        weight: "250g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 40,
        categoryId: categoryMap.get("dairy"),
        isActive: true,
      },

      // Snacks
      {
        name: "Mixed Nuts",
        description: "Premium mixed nuts perfect for healthy snacking",
        price: "300.00",
        originalPrice: "350.00",
        weight: "250g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 50,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Protein Bars",
        description: "High protein energy bars for fitness enthusiasts",
        price: "180.00",
        weight: "6 pieces",
        unit: "piece",
        imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 40,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Trail Mix",
        description: "Healthy trail mix with nuts, dried fruits and seeds",
        price: "250.00",
        weight: "200g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 35,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Granola Bars",
        description: "Crunchy granola bars made with oats and honey",
        price: "150.00",
        weight: "6 pieces",
        unit: "piece",
        imageUrl: "https://images.unsplash.com/photo-1590736969955-71cc94901144?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 45,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Roasted Almonds",
        description: "Lightly salted roasted almonds for healthy snacking",
        price: "400.00",
        weight: "250g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1508747703725-719777637510?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 30,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Dried Fruits Mix",
        description: "Assorted dried fruits rich in vitamins and minerals",
        price: "320.00",
        weight: "250g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 25,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Whole Grain Crackers",
        description: "Crispy whole grain crackers perfect with cheese",
        price: "120.00",
        weight: "200g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 40,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Popcorn",
        description: "Light and airy popcorn seasoned with natural flavors",
        price: "80.00",
        weight: "100g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 60,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Rice Cakes",
        description: "Light and crunchy rice cakes for guilt-free snacking",
        price: "100.00",
        weight: "150g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 35,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },
      {
        name: "Veggie Chips",
        description: "Crispy vegetable chips made from real vegetables",
        price: "140.00",
        weight: "100g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 30,
        categoryId: categoryMap.get("snacks"),
        isActive: true,
      },

      // Beverages
      {
        name: "Fresh Orange Juice",
        description: "Freshly squeezed orange juice with no added sugar",
        price: "120.00",
        weight: "1 liter",
        unit: "liter",
        imageUrl: "https://images.unsplash.com/photo-1544145945-f90425340c7e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 50,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Green Tea",
        description: "Premium green tea leaves rich in antioxidants",
        price: "200.00",
        weight: "100g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1564890275445-64d6ac8c9a89?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 30,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Coconut Water",
        description: "Natural coconut water packed with electrolytes",
        price: "60.00",
        weight: "500ml",
        unit: "ml",
        imageUrl: "https://images.unsplash.com/photo-1605275400606-2d3c0516e3ac?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 40,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Cold Coffee",
        description: "Refreshing cold coffee with rich coffee flavor",
        price: "80.00",
        weight: "300ml",
        unit: "ml",
        imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 45,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Herbal Tea",
        description: "Soothing herbal tea blend for relaxation and wellness",
        price: "180.00",
        weight: "50g",
        unit: "gram",
        imageUrl: "https://images.unsplash.com/photo-1597318066986-3920d3ab6cb4?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 25,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Lemon Water",
        description: "Refreshing lemon-infused water perfect for hydration",
        price: "40.00",
        weight: "500ml",
        unit: "ml",
        imageUrl: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 60,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Energy Drink",
        description: "Natural energy drink with vitamins and minerals",
        price: "100.00",
        weight: "250ml",
        unit: "ml",
        imageUrl: "https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 35,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Smoothie Mix",
        description: "Healthy smoothie mix with fruits and superfoods",
        price: "160.00",
        weight: "400ml",
        unit: "ml",
        imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 20,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Sparkling Water",
        description: "Refreshing sparkling water with natural bubbles",
        price: "70.00",
        weight: "750ml",
        unit: "ml",
        imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 50,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
      {
        name: "Fruit Punch",
        description: "Mixed fruit punch with natural fruit flavors",
        price: "90.00",
        weight: "500ml",
        unit: "ml",
        imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        stock: 30,
        categoryId: categoryMap.get("beverages"),
        isActive: true,
      },
    ];

    console.log("Inserting products...");
    await db.insert(products).values(sampleProducts);

    console.log("Database seeding completed successfully!");
    return {
      categories: insertedCategories.length,
      products: sampleProducts.length,
    };
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

// Run seeding if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedDatabase()
    .then((result) => {
      console.log(`Seeded ${result.categories} categories and ${result.products} products`);
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seeding failed:", error);
      process.exit(1);
    });
}
